server:
  port: 8090

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/v1/applications/**
          filters:
            - JwtAuthGatewayFilter

        - id: nlp-service
          uri: lb://nlp-service
          predicates:
            - Path=/api/v1/nlp/**
          filters:
            - JwtAuthGatewayFilter

        - id: ml-service
          uri: lb://ml-service
          predicates:
            - Path=/api/v1/ml/**
          filters:
            - JwtAuthGatewayFilter

        - id: anomaly-service
          uri: lb://anomaly-service
          predicates:
            - Path=/api/v1/anomalies/**
          filters:
            - JwtAuthGatewayFilter

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/v1/analytics/**
          filters:
            - JwtAuthGatewayFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - JwtAuthGatewayFilter

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - JwtAuthGatewayFilter
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: mySuperSecretKeyForUGCProject12345678901234567890