export function downloadPdfReport({
  title,
  subtitle,
  appId = "",
  metrics = [],
  sections = [],
  filename = "UGC_Compliance_Report.pdf",
}) {
  const dateStr = new Date().toLocaleDateString("en-IN", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      margin: 40px;
      color: #0f172a;
      background: #ffffff;
    }
    .header {
      border-bottom: 3px solid #0d9488;
      padding-bottom: 16px;
      margin-bottom: 24px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .govt-badge {
      font-size: 11px;
      font-weight: bold;
      letter-spacing: 1px;
      color: #0f766e;
      text-transform: uppercase;
    }
    h1 {
      font-size: 22px;
      margin: 4px 0;
      color: #0f172a;
    }
    p.sub {
      font-size: 13px;
      color: #64748b;
      margin: 0;
    }
    .meta-box {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 24px;
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      font-size: 12px;
    }
    .meta-item strong {
      display: block;
      color: #475569;
      font-size: 10px;
      text-transform: uppercase;
      margin-bottom: 2px;
    }
    .meta-item span {
      font-weight: bold;
      color: #0f172a;
    }
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 16px;
      margin-bottom: 24px;
    }
    .metric-card {
      border: 1px solid #cbd5e1;
      border-radius: 8px;
      padding: 14px;
      background: #ffffff;
    }
    .metric-title {
      font-size: 11px;
      font-weight: bold;
      color: #475569;
      text-transform: uppercase;
    }
    .metric-val {
      font-size: 24px;
      font-weight: 800;
      color: #0d9488;
      margin: 4px 0;
    }
    .footer {
      margin-top: 40px;
      border-top: 1px solid #e2e8f0;
      padding-top: 16px;
      font-size: 10px;
      color: #94a3b8;
      display: flex;
      justify-content: space-between;
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="govt-badge">University Grants Commission · Government of India</div>
      <h1>${title}</h1>
      <p class="sub">${subtitle}</p>
    </div>
    <div style="text-align: right; font-size: 11px; color: #64748b;">
      <div>Date: <strong>${dateStr}</strong></div>
      ${appId ? `<div>App ID: <strong>${appId}</strong></div>` : ""}
    </div>
  </div>

  <div class="meta-box">
    <div class="meta-item">
      <strong>Regulatory Framework</strong>
      <span>UGC Compliance Portal 2024-25</span>
    </div>
    <div class="meta-item">
      <strong>Verification Protocol</strong>
      <span>Automated NLP + ML XGBoost Validation</span>
    </div>
    <div class="meta-item">
      <strong>Status</strong>
      <span>OFFICIALLY VERIFIED</span>
    </div>
  </div>

  ${
    metrics.length > 0
      ? `<div class="metrics-grid">
    ${metrics
      .map(
        (m) => `<div class="metric-card">
      <div class="metric-title">${m.label}</div>
      <div class="metric-val">${m.val}</div>
      <div style="font-size:11px; color:#64748b;">${m.desc || ""}</div>
    </div>`
      )
      .join("")}
  </div>`
      : ""
  }

  ${sections
    .map(
      (sec) => `
    <div style="margin-bottom: 20px;">
      <h3 style="font-size: 14px; margin-bottom: 8px; color: #0f172a; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px;">${sec.title}</h3>
      <p style="font-size: 12px; line-height: 1.6; color: #334155;">${sec.content}</p>
    </div>
  `
    )
    .join("")}

  <div class="footer">
    <span>Generated by UGC Autonomous AI Compliance Microservices System</span>
    <span>Confidential · Official Regulatory Document</span>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 500);
    };
  </script>
</body>
</html>`;

  // 1. Trigger actual browser download of PDF Blob
  const blob = new Blob([htmlContent], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename.endsWith(".pdf") ? filename : `${filename}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // 2. Open print-ready tab to allow printing directly to PDF
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  }
}
