server:
  port: 8083

spring:
  application:
    name: anomaly-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ugc_anomaly_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
